@startsalt

{

{T

+ 기본목록(최근목록) => 대시보드(명세서목록, 유지보수기간)

 

++ 로그인

+++ 권한관리

 

++ 통합검색

+++ 유지보수기간 (재계약찾기)

++++ 만료여부

++++ 만료기간

+++ 검색항목2

+++ 검색항목3

+++ 검색항목N

 

++ 영업관리(기존 ECOUNT를 업그레이드) => ECOUNT API로 추가된 부분(유지보수부분)은 제거하고 입력해 줌

+++ 판매

++++ 판매조회(유지보수)

 

++ 자료입력/수정/검색(테이블별 입력창)

+++ 명세서입력

+++ 라이센스입력(~=유지보수내역)

+++ 지원이력입력

}

}

@endsalt